[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = { workspace = true }
tracing-error = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sea-orm = { workspace = true }
